@api_HostAddress = http://localhost:9001

GET {{api_HostAddress}}/api/user/profile/000000000000000000c0000000000000
Accept: application/json

###
GET {{api_HostAddress}}/api/user/profile/test?y=78
Accept: application/json