
services:
  bg-db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - bg-pgdata:/var/lib/postgresql
    networks:
      - syncup-network

  bg-pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@syncup.rocks
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - ./postgres/pgadmin.json:/pgadmin4/servers.json
    depends_on:
      - bg-db
    networks:
      - syncup-network

  bg-s3proxy:
    image: andrewgaul/s3proxy:latest
    container_name: s3proxy
    ports:
      - "5051:8080"
    environment:
      # No auth needed for local dev
      - S3PROXY_AUTHORIZATION=none
      - S3PROXY_ENDPOINT=http://0.0.0.0:8080
      # Use the modern filesystem-nio2 backend
      #- JCLOUDS_PROVIDER=filesystem-nio2
      # Use basic one for now - allows to easily pre-seed. but, if needing enhanced metadata, 
      # may want to switch to nio2 and add a separate metadata store and see with sync
      - JCLOUDS_PROVIDER=filesystem
      - JCLOUDS_FILESYSTEM_BASEDIR=/data
    volumes:
      # Mount your local folder containing your "buckets"
      - ./s3proxy:/data
    networks:
      - syncup-network

  bg-mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    networks:
      - syncup-network

  bg-keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # SMTP settings
      KC_EMAIL_SMTP_HOST: bg-mailhog
      KC_EMAIL_SMTP_PORT: 1025
      KC_EMAIL_SMTP_USER: ""
      KC_EMAIL_SMTP_PASSWORD: ""
      KC_EMAIL_FROM: no-reply@local.dev
      KC_EMAIL_SMTP_FROM_DISPLAY_NAME: "Dev Keycloak"
      KC_EMAIL_SMTP_ENCRYPTION: none
    ports:
      - "8080:8080"
    depends_on:
      - bg-mailhog
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
    networks:
      - syncup-network

  bg-traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true" # Enables dashboard at http://localhost:8080
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.file.filename=/etc/traefik_dynamic.yml"
    ports:
      - "7080:80"     # Browsing to http://syncup.local:7080
      - "7081:8080"   # Traefik Dashboard for debugging
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik_dynamic.yml:/etc/traefik_dynamic.yml"
    networks:
      - syncup-network

volumes:
  bg-pgdata:

networks:
  syncup-network:
    driver: bridge